server:
#  8081端口被占用，因此8081开始都加一变成从8082开始，
#这里本来是8083
  port: 8084
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.141:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.1.141
    username: leyou
    password: qwet1234
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
#    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
#    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}